DELETE from belt;
INSERT INTO belt (id, name, points) VALUES('1','whiteBelt','100');
INSERT INTO belt (id, name, points) VALUES('2','yellowBelt','200');
INSERT INTO belt (id, name, points) VALUES('3','orangeBelt','500');
INSERT INTO belt (id, name, points) VALUES('4','greenBelt','1000');
INSERT INTO belt (id, name, points) VALUES('5','blueBelt','1500');
INSERT INTO belt (id, name, points) VALUES('6','redBelt','2000');
INSERT INTO belt (id, name, points) VALUES('7','violetBelt','2500');
INSERT INTO belt (id, name, points) VALUES('8','brownBelt','3000');
INSERT INTO belt (id, name, points) VALUES('9','blackBelt','5000');
